name: NodeJS with Gulp

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      ## TODO: get version from package.json
      - name: Set enviroment for github-release
        id: tag
        run: |
          echo ::set-output name=RELEASE_TAG::"v1.3.0"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run build

      - name: cp php file
        run: |
          cp ./package.json ./build
          cp ./screenshot.png ./build
          cp ./*.php ./build
          cp -r ./assert ./build
          cp -r ./component ./build
          cp -r ./libray ./build
          cp -r ./js/lib ./build/js

      - name: cp cdn file to branche
        run: |
          git checkout gh-sourceg
          cp -r ./build/* ./
          git add .
          git commit -m "${{ steps.tag.outputs.RELEASE_TAG }}"
          git push origin gh-sourceg

      - name: upload assets
        uses: meeDamian/github-release@2.0
        with:
          allow_override: true
          token: ${{ secrets.GIT_HUB_TOKEN }}
          tag: ${{ steps.tag.outputs.RELEASE_TAG }}
          name: ${{ steps.tag.outputs.RELEASE_TAG }}
          files: build/
