name: RELEASE_TAG

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run build
          npm whoami

      - name: cp php file
        run: |
          mkdir -p build
          cp ./package.json ./build
          cp ./screenshot.png ./build
          cp ./*.php ./build
          cp -r ./assert ./build
          cp -r ./component ./build
          cp -r ./libray ./build
          cp -r ./js/lib ./build/js

      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          release-type: node
          extra-files: |
            build/*

        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
