name: RELEASE_TAG

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run build
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - name: cp php file
        run: |
          cp ./package.json ./build
          cp ./screenshot.png ./build
          cp ./*.php ./build
          cp -r ./assert ./build
          cp -r ./component ./build
          cp -r ./libray ./build
          cp -r ./js/lib ./build/js

        run: |
          git fetch
          git checkout gh-sourceg
          cp -r ./build/* ./
          git add .
          git commit -m "version:  ${{ steps.vars.outputs.tag }}"
          git push origin gh-sourceg

      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          release-type: node
          extra-files: |
            build/*

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
